name: My Workflow

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
           PROD_DATABASE_HOST: ${{ secrets.PROD_DATABASE_HOST }}
           PROD_DATABASE: ${{ secrets.PROD_DATABASE }}
           PROD_DATABASE_USER: ${{ secrets.PROD_DATABASE_USER }}
           PROD_DATABASE_PASSWORD: ${{ secrets.PROD_DATABASE_PASSWORD }}
            
        run: |

           sudo apt-get -y install mysql-client
           mysql --version
           crds="[mysqldump]\nuser=$PROD_DATABASE_USER
           \npassword=$PROD_DATABASE_PASSWORD\nhost=$PROD_DATABASE_HOST\nport=3306\ndatabase=$PROD_DATABASE"
           echo -e $crds > login.cnf
           cat login.cnf
           filename=$(date +%Y%m%dT%H%M%S)-backup
           mysqldump --defaults-extra-file=login.cnf | gzip > ${filename}.gz 

