# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  PROD_DATABASE_HOST: ${{ secrets.PROD_DATABASE_HOST }}
  PROD_DATABASE_USER: ${{ secrets.PROD_DATABASE_USER }}
  PROD_DATABASE_PASSWORD: ${{ secrets.PROD_DATABASE_PASSWORD }}

  # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install & Setup MySQL
      run: 
        sudo apt-get -y install mysql-client
        mysql --version
        crds="[mysqldump]\nuser=$PROD_DATABASE_USER
        \npassword=$PROD_DATABASE_PASSWORD\nhost=$PROD_DATABASE_HOST\nport=3306"
        echo -e $crds > login.cnf
        cat login.cnf

        filename=$(date +%Y%m%dT%H%M%S)-backup
        mysqldump --defaults-extra-file=login.cnf \
          --single-transaction \
          --events \
          --routines \
          --triggers \
          --databases test_gg | gzip > ${filename}.gz
        stat -c %s ${filename}.gz
        echo Done
