name: My Workflow

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |

           sudo apt-get -y install mysql-client
           mysql --version
           crds="[mysqldump]\nuser=$PROD_DATABASE_USER
           \npassword=$PROD_DATABASE_PASSWORD\nhost=$PROD_DATABASE_HOST\nport=3306"
           echo -e $crds > login.cnf
           cat login.cnf

           filename=$(date +%Y%m%dT%H%M%S)-backup
           mysqldump --defaults-extra-file=login.cnf \
           --single-transaction \
           --events \
           --routines \
           --triggers \
           --databases test_gg | gzip > ${filename}.gz
           stat -c %s ${filename}.gz
           echo Done
