name: My Workflow

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
           HOST : ${{ secrets.PROD_DATABASE_HOST }}
           DATABASE : ${{ secrets.PROD_DATABASE }}
           USER : ${{ secrets.PROD_DATABASE_USER }}
           PASSWORD : ${{ secrets.PROD_DATABASE_PASSWORD }}
            
        run: |

           sudo apt-get -y install mysql-client
           mysql --version
            
           filename=$(date +%Y%m%dT%H%M%S)-backup
           sudo mysqldump -u  $USER -h $HOST $DATABASE -P 3306 -p $PASSWORD  > $filename.sql

