name: My Workflow

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
           PROD_DATABASE_HOST: ${{ secrets.PROD_DATABASE_HOST }}
           PROD_DATABASE: ${{ secrets.PROD_DATABASE }}
           PROD_DATABASE_USER: ${{ secrets.PROD_DATABASE_USER }}
           PROD_DATABASE_PASSWORD: ${{ secrets.PROD_DATABASE_PASSWORD }}
            
        run: |

           sudo apt-get -y install mysql-client
           mysql --version
            
           filename=$(date +%Y%m%dT%H%M%S)-backup
           sudo mysqldump -u  $PROD_DATABASE_USER -h $PROD_DATABASE_HOST $PROD_DATABASE -P 3306 -p $PROD_DATABASE_PASSWORD  > $filename.sql

